server_name = "matrix.ваш-домен.ru"   # замените на ваш домен

[database]
backend = "postgres"
uri = "postgres://tuwunel_user:ghg6Random@postgres:5432/tuwunel" # ghg6Random - пароль от БД, можете заменить на свой, но незабудьте про docker-compose

[global]
address = "0.0.0.0:8008"              # слушаем внутри контейнера
media_directory = "/var/lib/tuwunel/media"

# Разрешаем регистрацию только по токену (для создания первого админа)
[registration]
enabled = true
token = "msecret123"   # замените на сгенерированный