server:
    directory: /opt/unbound
    username: unbound
    logfile: ""
    use-syslog: no
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 172.20.0.0/16 allow
    auto-trust-anchor-file: ""
    val-log-level: 2
    # Отключаем валидацию, если не нужна:
    val-permissive-mode: yes