server:
    # Слушаем все интерфейсы
    interface: 0.0.0.0
    # Разрешаем рекурсивные запросы
    access-control: 172.20.0.0/16 allow
    access-control: 127.0.0.1/32 allow

    # Включаем, если нужны логи для отладки (потом можно отключить)
    verbosity: 1

    # Доверять ли DNSSEC? (оставим включенным, как в образе)
    val-permissive-mode: no

    # Если хотите использовать форвардеры вместо корневых серверов,
    # раскомментируйте секцию ниже
# forward-zone:
#     name: "."
#     forward-tls-upstream: yes
#     forward-addr: 1.1.1.1@853#cloudflare-dns.com
#     forward-addr: 1.0.0.1@853#cloudflare-dns.com